### ISSUE TITLE
instructions on data preparation.

### ISSUE THREAD

**Issue by wangjksjtu** [gongzhitaao/tfmodels#1]
Thanks for your code, I am going to run your code on IMDB dataset. After decompressing the imdb.tar.gz file, I switched to data_utils folder. I have tried the scripts and got errors (I followed the instructions on README.org file).

Could you please write a detailed doc on how to run the code, especially data preparation? Thanks a lot.

**Comment by gongzhitaao** [comment]
Yes, there was a small bug.  I think you need to change [this line](https://github.com/gongzhitaao/tfmodels/blob/87259c41a9434db336d326e3ba284215ad2ca8fb/text-classifier/data_utils/reuters2_input.bash#L3), it should be where the data is stored.

I actually have updated this repo dramatically on my local machine.  So the code changed a lot.  I will update the code today and let you know.

**Comment by wangjksjtu** [comment]
Thanks a lot !!!

**Comment by gongzhitaao** [comment]
Updated the character-level pipeline.  It should be working now.  I will update word-level pipeline in a couple of days. :clinking_glasses:
